// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eticaret1;

namespace eticaret1.Migrations
{
    [DbContext(typeof(Program))]
    [Migration("20210725131343_first")]
    partial class first
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CategoryyProductt", b =>
                {
                    b.Property<int>("CategoryysCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProducttsProductId")
                        .HasColumnType("int");

                    b.HasKey("CategoryysCategoryId", "ProducttsProductId");

                    b.HasIndex("ProducttsProductId");

                    b.ToTable("CategoryyProductt");
                });

            modelBuilder.Entity("eticaret1_entity.Models.Categoryy", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categoryy");
                });

            modelBuilder.Entity("eticaret1_entity.Models.Productt", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Namee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Pricee")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Productt");
                });

            modelBuilder.Entity("CategoryyProductt", b =>
                {
                    b.HasOne("eticaret1_entity.Models.Categoryy", null)
                        .WithMany()
                        .HasForeignKey("CategoryysCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eticaret1_entity.Models.Productt", null)
                        .WithMany()
                        .HasForeignKey("ProducttsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
